In [2]:
import pandas as pd

data_products = {
    'ProductID': ['P1001', 'P1002', 'P1003', 'P1004', 'P1005', 'P1006', 'P1007', 'P1008', 'P1009', 'P1010',
                  'P1011', 'P1012', 'P1013', 'P1014', 'P1015'],
    'ProductName': ['Widget', 'Gadget', 'WidgetPro', 'Gizmo', 'Doodad', 'Thingy', 'Doohickey', 'Gimmick', 'Contraption', 'Device',
                    'Mechanism', 'Apparatus', 'Implement', 'Tool', 'Instrument'],
    'Price': [25.50, 45.75, 55.00, 12.95, 8.50, 22.50, 3.75, 7.80, 10.00, 33.50,
              45.00, 12.00, 14.95, 21.75, 17.50]
}
products = pd.DataFrame(data_products)

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
products.head()

  ProductID ProductName  Price
0     P1001      Widget  25.50
1     P1002      Gadget  45.75
2     P1003   WidgetPro  55.00
3     P1004       Gizmo  12.95
4     P1005      Doodad   8.50

In [5]:
data_sales = {
    'SaleID': list(range(101, 116)),
    'ProductID': ['P1001', 'P1003', 'P1002', 'P1005', 'P1001', 'P1006', 'P1007', 'P1008', 'P1009', 'P1004',
                  'P1010', 'P1011', 'P1013', 'P1014', 'P1015'],
    'Quantity': [3, 1, 2, 5, 10, 4, 2, 8, 1, 3, 7, 6, 3, 1, 2],
    'CustomerID': ['C001', 'C003', 'C002', 'C002', 'C001', 'C004', 'C005', 'C003', 'C005', 'C001',
                   'C002', 'C003', 'C004', 'C005', 'C001']
}
sales = pd.DataFrame(data_sales)

In [6]:
sales.head()

   SaleID ProductID  Quantity CustomerID
0     101     P1001         3       C001
1     102     P1003         1       C003
2     103     P1002         2       C002
3     104     P1005         5       C002
4     105     P1001        10       C001

In [7]:
data_customers = {
    'CustomerID': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007', 'C008', 'C009', 'C010',
                   'C011', 'C012', 'C013', 'C014', 'C015'],
    'CustomerName': ['Alpha Corp', 'Beta LLC', 'Gamma Inc', 'Delta Co', 'Epsilon Ltd', 'Zeta Inc', 'Eta LLC', 'Theta Corp', 'Iota PLC', 'Kappa LLC',
                     'Lambda Co', 'Mu Inc', 'Nu Ltd', 'Xi Corp', 'Omicron PLC'],
    'Location': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
                 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'Charlotte']
}
customers = pd.DataFrame(data_customers)

In [8]:
customers.head()

  CustomerID CustomerName     Location
0       C001   Alpha Corp     New York
1       C002     Beta LLC  Los Angeles
2       C003    Gamma Inc      Chicago
3       C004     Delta Co      Houston
4       C005  Epsilon Ltd      Phoenix

# **Tasks**

1. **What is the total revenue generated by each customer?**

In [9]:
sales = sales.merge(products, on="ProductID")
sales["Revenue"] = sales["Quantity"] * sales["Price"]


total_revenue_by_customer = sales.groupby("CustomerID")["Revenue"].sum().reset_index()
total_revenue_by_customer

  CustomerID  Revenue
0       C001   405.35
1       C002   368.50
2       C003   387.40
3       C004   134.85
4       C005    39.25

In [10]:
sales.head()

   SaleID ProductID  Quantity CustomerID ProductName  Price  Revenue
0     101     P1001         3       C001      Widget  25.50     76.5
1     102     P1003         1       C003   WidgetPro  55.00     55.0
2     103     P1002         2       C002      Gadget  45.75     91.5
3     104     P1005         5       C002      Doodad   8.50     42.5
4     105     P1001        10       C001      Widget  25.50    255.0

2. **Which product has the highest total sales revenue?**

In [11]:
highest_revenue_product = sales.groupby("ProductID")["Revenue"].sum().idxmax()
highest_revenue_product

'P1001'

3. **How many unique customers bought each product?**

In [12]:
unique_customers_per_product = sales.groupby("ProductID")["CustomerID"].nunique()
unique_customers_per_product

ProductID
P1001    1
P1002    1
P1003    1
P1004    1
P1005    1
P1006    1
P1007    1
P1008    1
P1009    1
P1010    1
P1011    1
P1013    1
P1014    1
P1015    1
Name: CustomerID, dtype: int64

4. **Which customer bought the most units of any single product in a transaction?**

In [13]:
most_units_customer = sales.loc[sales["Quantity"].idxmax(), ["CustomerID", "ProductID", "Quantity"]]
most_units_customer

CustomerID     C001
ProductID     P1001
Quantity         10
Name: 4, dtype: object

5. **What is the average price of the products purchased by each customer?**

In [14]:
avg_price_per_customer = sales.groupby("CustomerID")["Price"].mean()
avg_price_per_customer

CustomerID
C001    20.362500
C002    29.250000
C003    35.933333
C004    18.725000
C005    11.833333
Name: Price, dtype: float64

6. **List all products bought by customers located in 'New York'.**

In [15]:
ny_customers = customers[customers["Location"] == "New York"]["CustomerID"]
ny_products = sales[sales["CustomerID"].isin(ny_customers)]["ProductName"].unique()
ny_products

array(['Widget', 'Gizmo', 'Instrument'], dtype=object)

7. **Which location had the highest number of distinct products sold?**

In [16]:
sales_with_location = sales.merge(customers, on="CustomerID")

distinct_products_per_location = sales_with_location.groupby("Location")["ProductID"].nunique()
highest_product_location = distinct_products_per_location.idxmax()
print(highest_product_location)

Chicago

8. **What is the total quantity of products sold in 'Los Angeles'?**

In [17]:
total_qty_la = sales_with_location[sales_with_location["Location"]== "Los Angeles"]["Quantity"].sum()
total_qty_la

14

9. **Identify the customer who has spent the most money on a single transaction.**

In [18]:
most_spend_money_cst = sales.loc[sales["Revenue"].idxmax(), ["CustomerID", "Revenue"]]
most_spend_money_cst

CustomerID     C003
Revenue       270.0
Name: 11, dtype: object

10. **Which product is the most popular in terms of quantity sold?**

In [19]:
popular_product = sales.groupby("ProductID")["Quantity"].count().idxmax()
popular_product

'P1001'

In [20]:
most_popular_product = sales.groupby("ProductID")["Quantity"].sum().idxmax()
most_popular_product

'P1001'

11. **How many transactions have occurred in each location?**

In [21]:
sales.head()

transactions_per_location = sales_with_location.groupby("Location")["SaleID"].count()
transactions_per_location

Location
Chicago        3
Houston        2
Los Angeles    3
New York       4
Phoenix        3
Name: SaleID, dtype: int64

12. **What is the average number of items per transaction for each location?**

In [22]:
avg_tran_per_location = sales_with_location.groupby("Location")["Quantity"].mean()
avg_tran_per_location

Location
Chicago        5.000000
Houston        3.500000
Los Angeles    4.666667
New York       4.500000
Phoenix        1.333333
Name: Quantity, dtype: float64

13. **Which customer has the widest variety of products purchased?**

In [23]:
widest_variety_customer = sales_with_location.groupby("CustomerID")["ProductID"].nunique().idxmax()
widest_variety_customer

'C001'

14. **For each product, how many transactions were above the average price of all products?**

In [24]:
avg_price = products["Price"].mean()
above_avg = sales[sales["Price"] > avg_price].groupby("ProductID")["SaleID"].count()
above_avg

ProductID
P1001    2
P1002    1
P1003    1
P1006    1
P1010    1
P1011    1
Name: SaleID, dtype: int64




15. **Which customer has never bought the same product twice?**

In [25]:
unique_product_customers = sales["CustomerID"][sales.groupby(["CustomerID", "ProductID"])["ProductID"].transform("count") == 1].unique()
unique_product_customers

array(['C003', 'C002', 'C004', 'C005', 'C001'], dtype=object)